### ISSUE TITLE
Explanation of Radar Point Cloud Field

### ISSUE THREAD

**Issue by hoangvietdo** [SangwooJung98/Co-RaL-Dataset#1]
Hi,

Thank you very much for making the dataset open-source.

I have a question regarding the radar point cloud fields.
Specifically, I would like to understand the definitions of "intensity" and "az".
Does "intensity" refer to the Radar Cross Section (RCS) or the noise level?

Thank you!

**Comment by SangwooJung98** [comment]
Hi, 

Thank you for your interest in our dataset. 

The intensity field should have been the RCS level of each point, but due to the sensor driver issue, the RCS values of a single scan are fixed with the same value (more specifically, the same as a single point included in the scan). 
"az" means the distance between the point and sensor (sensed distance). 
This value is provided for the convenience of calculating the angular coordinate of each point. 

If you want to use only data given from the original sensor driver (not the ones that I have generated for my convenience), I recommend you to exploit only "x, y, z, vr" channel information as those channels are direct values from the sensor. 

Thank you
