### ISSUE TITLE
Question on the decoupled RANSAC/LSQ

### ISSUE THREAD

**Issue by hoangvietdo** [SangwooJung98/Co-RaL-Dataset#2]
Hi,

I have a question regarding the decoupled RANSAC/LSQ method proposed in your paper. I implemented the RANSAC/LSQ algorithm as described in reference [10] and extended it with the decoupling approach from your paper. However, my velocity estimation results are significantly worse compared to the traditional RANSAC/LSQ method (especially the z direction).

Here is the process I followed:

1. Converted the Cartesian point cloud to polar coordinates.
2. Computed v_xy using RANSAC/LSQ (I used SVD to solve the linear equations).
3. Computed v_xz using RANSAC/LSQ with v_x from the previous step as a linear constraint (I used ```lsqlin``` function from MATLAB). 
     -I also tried using the standard RANSAC/LSQ for this step, ignoring v_x to reduce computation time compared to using ```lsqlin```. Although the result improved, it was still worse than the traditional method.

Did I misunderstand any part of the method? Additionally, would it be possible for you to open source the code for this section to allow for comparison?

Thanks!

**Comment by SangwooJung98** [comment]
Hi, 

Thank you for your interest in our algorithm. 
Firstly, LSQ should be done after the double RANSAC on the xy plane and yz plane. 
As LSQ is prone to noise and dynamic objects, we exploited only inlier points that passed through the double RANSAC strategy. 
Inliers from the first RANSAC should be exploited as the input for the second RANSAC to calculate more accurate z-axis velocity. 
Secondly, as the z-axis odometry result may vary following the initial roll and pitch angles of the system, gravity-based initial orientation must be done before calculating the trajectory using the ego velocity. (Due to the limited pages of the paper, gravity-based initial orientation is only included in Fig. 2. The process is similar to the pose initialization that is widely exploited on LiDAR-IMU SLAM algorithms. )
We exploited the very first 1 second of time that the robot is not moving to calculate the initial orientation of the robot. 
Lastly, as we're extending our work, we do not have a plan for open-sourcing the code yet. 

Thank you
